### ISSUE TITLE
UUIDs

### ISSUE THREAD

**Issue by rupert** [renalreg/radar#127]
All objects in the UKRDC should have a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier). Currently data is received in the PatientView feed without any sort of ID - so we'll need to generate a UUID for each object. We could use [UUID version 5](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_5_.28SHA-1_hash_.26_namespace.29) for this. The UUID v5 namespace could be the renal unit and patient ID. The UUID v5 name could be the object's position in the file or perhaps a field that is unlikely to change like the date. Eventually renal units will send in UUIDs themselves.

Radar will use a UUID as the primary key (rather than an integer) which will make it easy to merge data from the UKRDC with data entered on Radar (very low probability of collisions). It will also be useful for following data as it moves between systems.

**Comment by George-D-S** [comment]
Another possibility for the Renal Units would be something based on https://www.gs1uk.org/get-a-barcode/for-healthcare

**Comment by rupert** [comment]
In Python it would look something like this:

```python
>>> from uuid import uuid5, UUID
>>> unit_id = 'REE01',
>>> patient_id = '1000000001'
>>> unit = uuid5(UUID('00000000-0000-0000-0000-000000000000'), unit_id)
>>> unit
UUID('e0a42492-35dd-5099-a3ad-0f65a5346b65')
>>> patient = uuid5(unit, patient_id)
>>> patient
UUID('0fe8f6cd-566b-58d9-a02b-c81db9bd7c96')
>>> medications = [uuid5(patient, str(x)) for x in xrange(1, 4)]
[UUID('866066fb-128e-5324-9a27-4d5fb51c81ab'), UUID('8bcdeeac-ce9c-59d0-a2aa-df96b70da736'), UUID('2e1b16ac-05c2-5980-a539-15851d83cfc6')]
```

Radar will probably use a scheme like this to turn a non-UUID ID into a UUID. As far as I can tell GS1 IDs are randomly generated in a particular namespace (sort of like a cross between UUID v4 and v5).

Radar is now using v4 UUIDs as the PK in all of the patient data tables (medications, dialysis etc).
